apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: resource-collector-rc8q4w2z
  annotations:
    description: Global resource collector - fetches public data, normalizes to JSON-LD
    wasmcloud.dev/categories: go,mcp,collector,global
spec:
  components:
    - name: resource-collector-component
      type: component
      properties:
        image: file://./build/resource_collector_component_s.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
    - name: grpc-provider
      type: capability
      properties:
        image: ghcr.io/wasmcloud/grpc-provider:0.3.0
      traits:
        - type: link
          properties:
            target: resource-collector-component
            namespace: wrpc
            package: grpc
            interfaces:
              - server
            source_config:
              - name: grpc-server-config
                properties:
                  port: "8081"
                  reflection: "true"
